"""Application shell: title bar, sub-header, scrolling device list, event pump.

Threading model
---------------
Everything in this module runs on the Tk main thread. Worker threads never
touch a widget; they put `DeviceEvent` values on a queue which `_pump` drains
on a timer, applies to backend state, and then renders. That is the only path
by which network activity reaches the UI.

    ConnectionWorker thread -> Queue -> _pump (Tk thread) -> card.render()

Window chrome
-------------
The design draws its own title bar, so the native caption has to go. Rather
than `overrideredirect(True)` -- which also costs taskbar presence, snap,
minimise animation and resize borders, all of which then need reimplementing --
this clears only WS_CAPTION from the window style via ctypes and keeps
WS_THICKFRAME. The result is a captionless window that Windows still treats as
a normal one, so resizing and snapping keep working and the traffic lights only
have to drive close/minimise/maximise.

`overrideredirect` remains a fallback for non-Windows, where the app is not
targeted but should still start.
"""

from __future__ import annotations

import logging
import time

import customtkinter as ctk

from . import fonts, icons, theme
from . import splash as splash_module
from .anim import Pulse
from .backend.config_manager import ConfigManager
from .backend.device_manager import DeviceManager, DeviceState
from .backend.events import ConnectionState
from .backend.logging_setup import shutdown_logging
from .shell import chrome, commands, handoff
from .shell.subheader import SubHeader
from .splash import LaunchSplash
from .widgets.add_device import AddDeviceButton
from .widgets.device_card import DeviceCard
from .widgets.dialogs import ConfirmDialog, ErrorReporter
from .widgets.title_bar import TitleBar

logger = logging.getLogger("emcc.app")

#: Event drain interval. 10 Hz keeps the UI responsive without spinning: at 25
#: devices the backend produces ~25 events/s (temperature is throttled to 1 Hz
#: per device), so a tick typically has two or three events to apply.
PUMP_INTERVAL_MS = 100

#: Cards built before the window is shown. Enough to fill the viewport at the
#: default window height (142px card + 12px gap); the rest stream in on idle.
INITIAL_CARDS = 5

#: Attributes that `tests/` and `tools/visual_pass.py` reach on `App` from
#: outside, minus the seven that resolve on `customtkinter.CTk` and so never
#: reach `__getattr__` at all. The four-slice modularisation moves the code
#: behind several of these into `shell/` and `views/`; each must stay
#: reachable on `App` under its current name, because 174 call sites outside
#: `emcc/` use them and are not being rewritten.
#:
#: Generated by the scan in `test_facade_covers_every_name_reached_from_outside`
#: rather than typed. This list was wrong three times in one day -- 19, 24 and
#: 26 all in circulation -- and every time the wrongness was silent, because
#: nothing failed when it drifted. That test is what keeps it honest; do not
#: hand-edit this set without running it.
_FACADE_NAMES: frozenset[str] = frozenset({
    "_add_device", "_build_remaining", "_caption", "_cards",
    "_clean_device", "_confirm_remove", "_connect_device", "_hint",
    "_list", "_logo", "_order", "_pending_devices", "_pump",
    "_refresh_chrome", "_remove_device", "_render_device",
    "_scroll_to_end", "_shutting_down", "_toggle_auto",
    "config_manager", "manager", "pulse", "shutdown", "title_bar"
})

#: Gap between streamed cards. A timer, not `after_idle`: a single
#: `update_idletasks()` drains an entire after_idle chain, because each
#: callback re-queues before the queue is checked again -- which silently
#: turns the progressive build back into a blocking one.
CARD_BUILD_INTERVAL_MS = 1


class App(ctk.CTk):
    #: The facade contract, as a class attribute so callers reach it as
    #: `App._FACADE`. Same frozenset object as the module-level
    #: `_FACADE_NAMES`, which is what `__getattr__` reads -- it consults the
    #: module global rather than `self._FACADE` deliberately, since an
    #: attribute lookup inside `__getattr__` is how you get infinite
    #: recursion the first time the attribute is genuinely absent.
    _FACADE = _FACADE_NAMES

    def __init__(self, config: ConfigManager | None = None):
        super().__init__(fg_color=theme.APP_BG)

        self.title(theme.APP_TITLE)
        self.geometry(f"{theme.WINDOW_W}x{theme.WINDOW_H}")
        self.minsize(theme.WINDOW_MIN_W, theme.WINDOW_MIN_H)

        # A new Tk interpreter invalidates every cached CTkImage and CTkFont
        # (they hold interpreter-owned handles), so drop both caches before any
        # widget is built. See the note in icons.py.
        icons.clear_cache()
        fonts.clear_cache()
        fonts.init()
        self.pulse = Pulse(self)

        self.config_manager = config or ConfigManager()
        if config is None:
            self.config_manager.load()
        self.config_manager.on_save_error = self._on_config_save_error

        # DeviceManager owns the timers but not Tk: it gets a scheduler.
        self.manager = DeviceManager(
            self.config_manager,
            schedule=lambda delay_ms, fn: self.after(delay_ms, fn),
            cancel=self.after_cancel,
        )
        self.manager.on_device_changed = self._render_device

        self._cards: dict[str, DeviceCard] = {}
        self._order: list[str] = []
        self._offsets: dict[bool, float] = {}
        #: Variants with a measurement already queued, so a card that
        #: re-renders before it lands cannot pile up callbacks.
        self._measuring: set[bool] = set()
        self._drag_origin = (0, 0)
        self._maximised = False
        self._shutting_down = False
        self._pump_job: str | None = None
        self._build_job: str | None = None
        self._pending_devices: list[DeviceState] = []
        self._errors = ErrorReporter(self)
        self._splash: LaunchSplash | None = None
        self._splash_job: str | None = None
        self._splash_deadline = 0.0
        self._splash_ready_polls = 0

        self._strip_caption()

        self.title_bar = TitleBar(
            self, self.pulse,
            on_close=self.shutdown,
            on_minimise=self._minimise,
            on_maximise=self._toggle_maximise,
            on_drag_start=self._drag_start,
            on_drag_move=self._drag_move,
        )
        self.title_bar.pack(fill="x")

        self._build_subheader()
        self._build_list()
        self._rebuild()

        # Alt+F4 and any OS-level close must run the same teardown as the
        # traffic light, or shutdown is silently skipped.
        self.protocol("WM_DELETE_WINDOW", self.shutdown)
        self._start_pump()

        # Pre-render the launch splash off the UI thread. ~390ms of pure
        # Pillow work, deliberately not done on click: the splash has to
        # appear the instant the operator asks for it.
        self.after(500, splash_module.prepare)

    # ------------------------------------------------------------------
    # Window chrome
    # ------------------------------------------------------------------

    def _strip_caption(self) -> None:
        chrome.strip_caption(self)

    def _drag_start(self, event) -> None:
        chrome.drag_start(self, event)

    def _drag_move(self, event) -> None:
        chrome.drag_move(self, event)

    def _minimise(self) -> None:
        chrome.minimise(self)

    def _toggle_maximise(self) -> None:
        chrome.toggle_maximise(self)

    # ------------------------------------------------------------------
    # Sub-header
    # ------------------------------------------------------------------

    def _build_subheader(self) -> None:
        """Build the banner via the `SubHeader` builder.

        `_logo` is assigned **only when the wordmark loaded**, which is what
        this did before the extraction: on a failed load `App` has no `_logo`
        attribute at all. Since `_logo` is in `_FACADE_NAMES`, the absence is
        now reported by `__getattr__` naming the facade rather than as a Tcl
        error -- but the absence itself is pre-existing behaviour and is
        preserved deliberately, not tidied away into a `None`.
        """
        sub = SubHeader(self)
        self._caption = sub.caption
        if sub.logo is not None:
            self._logo = sub.logo

    # ------------------------------------------------------------------
    # Device list
    # ------------------------------------------------------------------

    def _build_list(self) -> None:
        """flex-1 px-8 py-4 flex flex-col gap-3, scrolling past the threshold."""
        self._list = ctk.CTkScrollableFrame(
            self,
            fg_color="transparent",
            corner_radius=0,
            scrollbar_button_color=theme.SCROLL_THUMB,
            scrollbar_button_hover_color=theme.SCROLL_THUMB_HOVER,
            scrollbar_fg_color="transparent",
        )
        self._list.pack(fill="both", expand=True,
                        padx=theme.PAGE_PAD_X - 8, pady=theme.PAGE_PAD_Y)

        # .device-scroll is 5px wide; CTkScrollbar defaults to 16 and stops
        # rendering a usable thumb below ~8, so 8 is the closest faithful value.
        bar = getattr(self._list, "_scrollbar", None)
        if bar is not None:
            bar.configure(width=8)

        # The add button and the scroll hint are created ONCE and stay put --
        # new cards are inserted before the button. Recreating them per add is
        # what made adding a device redraw the entire list.
        self._add_button = AddDeviceButton(self._list, on_click=self._add_device)
        self._add_button.pack(fill="x", pady=(theme.CARD_GAP + 4, 0))

        self._hint = ctk.CTkLabel(
            self._list, text="", font=fonts.sans(10.5),
            text_color=theme.TEXT_SCROLL_HINT, height=14,
        )
        self._hint_shown = False
        self._scrollbar_visible = True   # CTkScrollableFrame grids it by default

    def __getattr__(self, name: str):
        """Keep a lost facade attribute from being reported as a Tcl error.

        `tkinter.Tk.__getattr__` delegates every unknown attribute to the
        interpreter object, so before this override a missing `_hint` raised
        *"'_tkinter.tkapp' object has no attribute '_hint'"* -- which names the
        Tcl interpreter and never mentions `App`, giving a reader no reason to
        suspect the modularisation. Measured on a bare `CTk`, not inferred.

        Only `_FACADE` names are intercepted. Everything else keeps Tk's
        delegation, because CTk internals genuinely reach Tcl methods through
        it (`call`, `eval`, `createcommand`); narrowing that would break the
        toolkit rather than the facade.

        Safe to blame the modularisation here **only because facade properties
        raise `RuntimeError`, never `AttributeError`** -- see
        `VIEW_CONTRACT.md:151`. An `AttributeError` from inside a property
        would be swallowed by Python's attribute machinery and routed here,
        where this message would blame a missing attribute for what is really
        an unwired collaborator. With that rule held, an interception is
        genuinely a missing name.
        """
        if name in _FACADE_NAMES:
            raise AttributeError(
                f"'App' has no attribute {name!r}. It is a facade attribute "
                f"reached from tests/ or tools/, so it was most likely lost "
                f"during the modularisation -- see _FACADE in app.py."
            )
        return super().__getattr__(name)

    def _set_scrollbar_visible(self, visible: bool) -> None:
        """The design only shows the scrollbar at >= 4 devices.

        Guarded on the current state: re-applying grid() to an already-gridded
        widget re-runs its geometry and triggers CTkScrollbar._draw. This is
        called on every chrome refresh, so the no-op case has to be a no-op.
        """
        if visible == self._scrollbar_visible:
            return
        bar = getattr(self._list, "_scrollbar", None)
        if bar is None:
            return
        if visible:
            bar.grid()
        else:
            bar.grid_remove()
        self._scrollbar_visible = visible

    def _new_card(self, device: DeviceState, first: bool,
                  label_offset: float | None = None) -> DeviceCard:
        card = DeviceCard(
            self._list, device,
            on_connect=self._connect_device,
            on_clean=self._clean_device,
            on_auto=self._toggle_auto,
            on_temperature=self._open_temperature,
            on_remove=self._confirm_remove,
            on_rename=self.manager.rename_device,
            on_ip_change=self.manager.set_ip,
            pulse=self.pulse,
            label_offset=label_offset,
        )
        card.pack(fill="x", pady=(0 if first else theme.CARD_GAP, 0),
                  before=self._add_button)
        self._cards[device.id] = card
        self._order.append(device.id)
        return card

    def _rebuild(self) -> None:
        """Build the initial list, progressively.

        A card is ~90 CustomTkinter widgets and costs a few hundred
        milliseconds, essentially all of it Tcl round-trips. Building 25 of
        them before the window appears measured **11.1 seconds** of blank
        screen, which fails the "responsive with 25+ devices" requirement
        outright.

        So only enough cards to fill the viewport are built synchronously; the
        rest stream in one per idle tick. The window is up and interactive in
        well under a second, and the remaining cards appear as the operator is
        still reading the first ones. Scrolling before they finish simply shows
        them arriving, which is far better than showing nothing at all.
        """
        for card in self._cards.values():
            card.destroy()
        self._cards.clear()
        self._order.clear()
        self._pending_devices = list(self.manager.devices)

        for _ in range(INITIAL_CARDS):
            if not self._build_next_card():
                break

        self._align_all()
        self._refresh_chrome()

        if self._pending_devices:
            self._build_job = self.after(CARD_BUILD_INTERVAL_MS, self._build_remaining)

    def _build_next_card(self) -> bool:
        """Build the next queued card. False when the queue is empty."""
        if not self._pending_devices:
            return False
        device = self._pending_devices.pop(0)
        # A device could have been removed while still queued.
        if self.manager.get(device.id) is None:
            return bool(self._pending_devices)
        offset = self._offsets.get(device.temperature_alert)
        self._new_card(device, first=len(self._cards) == 0, label_offset=offset)
        return True

    def _build_remaining(self) -> None:
        """Stream in the rest of the cards, one per idle tick.

        Deliberately does NOT call `update_idletasks()`. Doing so re-enters
        Tk's idle queue and drains this whole chain in a single pass, which
        silently turns the progressive build back into a blocking one -- the
        exact bug this replaced. The label offset is taken from the cache that
        `_align_all` seeded from the first batch, so no measurement is needed;
        a card whose variant has no cached offset is aligned later by
        `_render_device`.
        """
        self._build_job = None
        if self._shutting_down or not self._pending_devices:
            self._pending_devices = []
            return
        self._build_next_card()
        self._refresh_chrome()
        if self._pending_devices:
            self._build_job = self.after(CARD_BUILD_INTERVAL_MS, self._build_remaining)

    def _align_all(self) -> None:
        """One shared alignment pass, seeding the per-variant offset cache.

        Each card's alignment needs computed geometry, so doing it per card
        would mean one forced relayout per card. Batching keeps startup to a
        single pass, and the offsets learned here let every card added later
        skip measuring entirely.
        """
        self.update_idletasks()
        for card in self._cards.values():
            offset = card.align_labels()
            if offset is not None:
                self._offsets[card.variant] = offset

    def _refresh_chrome(self) -> None:
        """Scroll hint, scrollbar visibility, sub-header caption, title bar."""
        total = len(self.manager.devices)
        scrolling = total >= theme.SCROLL_THRESHOLD

        # No device cap: the design's "supports up to 25" was a demo limit.
        self._hint.configure(text=f"Scroll to view all {total} devices")
        if scrolling != self._hint_shown:
            if scrolling:
                self._hint.pack(pady=(8, 4))
            else:
                self._hint.pack_forget()
            self._hint_shown = scrolling

        self._set_scrollbar_visible(scrolling)

        self._caption.configure(
            text=f"{total} device{'' if total == 1 else 's'} configured · "
                 "click Connect to establish TCP connection"
        )
        self.title_bar.update_status(
            connected=self.manager.connected_count,
            total=total,
            alerts=self.manager.alert_count(),
        )

    # ------------------------------------------------------------------
    # Event pump
    # ------------------------------------------------------------------

    def _start_pump(self) -> None:
        self._pump_job = self.after(PUMP_INTERVAL_MS, self._pump)

    def _pump(self) -> None:
        """Drain backend events and re-render only the cards that changed."""
        self._pump_job = None
        # Also guard on the widget still existing: destroy() without a prior
        # shutdown() (a harness, or an unexpected teardown) leaves this timer
        # pending, and Tk then reports `invalid command name "..._pump"`.
        if self._shutting_down or not self.winfo_exists():
            return
        try:
            changed = self.manager.drain_events()
            for device_id in changed:
                self._render_device(device_id)
            if changed:
                self._refresh_chrome()
        except Exception:
            # The pump must survive anything, or the UI stops updating.
            logger.exception("event pump iteration failed")
        finally:
            if not self._shutting_down:
                self._start_pump()

    def _render_device(self, device_id: str) -> None:
        card = self._cards.get(device_id)
        device = self.manager.get(device_id)
        if card is None or device is None:
            return   # removed while an event was in flight

        card.render()

        # A card that gains or loses the "Exceeds threshold" caption changes
        # its tallest column, so its label baseline moves.
        offset = self._offsets.get(card.variant)
        if offset is None:
            # First card of this shape: measuring needs a layout flush, which
            # measured 208ms inside a pump tick. Deferred to the next idle slot
            # so the tick stays fast -- the card renders one frame at the old
            # baseline, which is imperceptible, and every later card of this
            # shape uses the cached value.
            variant = card.variant
            if variant not in self._measuring:
                self._measuring.add(variant)
                self.after_idle(lambda: self._measure_variant(device_id, variant))
        elif card._label_offset != offset:
            for section in card._sections:
                section.set_top(offset)
            card._label_offset = offset

        self._announce_faults(device)

    def _measure_variant(self, device_id: str, variant: bool) -> None:
        """Measure and cache the label offset for a card shape, once.

        Runs off the pump tick (see _render_device). Guarded on the card still
        existing, because a device can be removed between scheduling and firing.
        """
        self._measuring.discard(variant)
        if self._shutting_down:
            return
        card = self._cards.get(device_id)
        if card is None or not card.winfo_exists():
            return
        self.update_idletasks()
        offset = card.align_labels()
        if offset is not None:
            self._offsets[card.variant] = offset

    def _announce_faults(self, device: DeviceState) -> None:
        """Pop a dialog only for faults worth interrupting the operator for.

        Nothing pops for an unexpected disconnect or a retry -- the card shows
        those. Only a final failure does, coalesced across devices.
        """
        if self._shutting_down or device.connection is not ConnectionState.ERROR:
            device.fault_announced = False
            return
        if device.fault_announced:
            return
        device.fault_announced = True
        self._errors.report(device.name, device.ip,
                            device.last_error or "Connection failed")

    # ------------------------------------------------------------------
    # Device actions
    # ------------------------------------------------------------------

    def _connect_device(self, device_id: str) -> None:
        commands.connect_device(self, device_id)

    def _clean_device(self, device_id: str) -> None:
        commands.clean_device(self, device_id)

    def _toggle_auto(self, device_id: str) -> None:
        commands.toggle_auto(self, device_id)

    def _open_temperature(self, device_id: str) -> None:
        commands.open_temperature(self, device_id)

    # ------------------------------------------------------------------
    # Launch splash
    # ------------------------------------------------------------------

    def _show_launch_splash(
        self, name: str, ip: str, existing: list[int], attempt: int = 0
    ) -> None:
        handoff.show_launch_splash(self, name, ip, existing, attempt)

    def _poll_pygui(self, ip: str, existing: list[int]) -> None:
        handoff.poll_pygui(self, ip, existing)

    def _on_splash_dismissed(self) -> None:
        handoff.on_splash_dismissed(self)

    def _add_device(self) -> None:
        """Append one card in place, leaving the existing ones untouched."""
        if self._shutting_down:
            return
        device = self.manager.add_device()
        offset = self._offsets.get(False)   # a new device is never in alert
        card = self._new_card(device, first=len(self._cards) == 1,
                              label_offset=offset)
        self._refresh_chrome()
        if offset is None:
            self.after_idle(lambda: self._settle(card))
        else:
            self.after_idle(self._scroll_to_end)

    def _settle(self, card: DeviceCard) -> None:
        if not card.winfo_exists():
            return
        # This flush is load-bearing, not defensive. Until layout has actually
        # run, a section's group still reports CTkFrame's *default* requested
        # height (200), so align_labels() would compute a negative offset,
        # clamp it to 0, and top-align the new card's labels.
        self.update_idletasks()
        offset = card.align_labels()
        if offset is not None:
            self._offsets[card.variant] = offset
        self._scroll_to_end()

    def _scroll_to_end(self) -> None:
        if self._shutting_down:
            return
        canvas = getattr(self._list, "_parent_canvas", None)
        if canvas is not None:
            canvas.yview_moveto(1.0)

    def _confirm_remove(self, device_id: str) -> None:
        device = self.manager.get(device_id)
        if device is None:
            return
        detail = f"{device.ip}\n\n" if device.ip else ""
        if device.connection.is_live:
            detail += "This device is connected. Its connection will be closed."
        else:
            detail += "This cannot be undone."
        ConfirmDialog(
            self,
            f"Remove {device.name}?",
            detail,
            on_confirm=lambda: self._remove_device(device_id),
        )

    def _remove_device(self, device_id: str) -> None:
        card = self._cards.pop(device_id, None)
        if device_id in self._order:
            self._order.remove(device_id)
        self.manager.remove_device(device_id)
        if card is not None:
            card.destroy()
        self._repack_first_card()
        self._refresh_chrome()

    def _repack_first_card(self) -> None:
        """Keep the top card flush; only later cards carry the gap-3 margin."""
        for index, device_id in enumerate(self._order):
            card = self._cards.get(device_id)
            if card is not None:
                card.pack_configure(pady=(0 if index == 0 else theme.CARD_GAP, 0))

    # ------------------------------------------------------------------
    # Errors and shutdown
    # ------------------------------------------------------------------

    def _on_config_save_error(self, exc: Exception) -> None:
        """Called by ConfigManager after repeated save failures."""
        if self._shutting_down:
            return
        self._errors.show_now(
            "Configuration", str(self.config_manager.path),
            f"Device settings could not be saved: {exc}")

    def shutdown(self) -> None:
        """Ordered teardown. Safe to call more than once."""
        if self._shutting_down:
            return
        self._shutting_down = True
        logger.info("shutdown requested")

        # 1. stop accepting new work
        for attribute in ("_pump_job", "_build_job"):
            job = getattr(self, attribute, None)
            if job is not None:
                try:
                    self.after_cancel(job)
                except Exception:
                    pass
                setattr(self, attribute, None)
        self._pending_devices = []
        self._errors.close()
        if self._splash is not None:
            self._splash.close()
            self._splash = None

        # 2. persist the latest device config before anything can block
        try:
            self.config_manager.flush()
        except Exception:
            logger.exception("shutdown: config flush failed")

        # 3. stop workers: signal all, then join with a shared budget
        try:
            self.manager.shutdown(timeout_s=4.0)
        except Exception:
            logger.exception("shutdown: worker teardown failed")

        # 4. close any open child windows -- dialogs and the temperature
        #    placeholder are Toplevels, and one left open outlives the root it
        #    was created against.
        for child in list(self.winfo_children()):
            if isinstance(child, ctk.CTkToplevel):
                try:
                    child.grab_release()
                except Exception:
                    pass
                try:
                    child.destroy()
                except Exception:
                    pass

        # 5. stop animations, then tear down Tk
        try:
            self.pulse.stop_all()
        except Exception:
            pass

        # destroy() must happen no matter what. If it is skipped, the root
        # leaks and -- because ImageTk.PhotoImage binds to
        # tkinter._default_root -- every image created by a *later* root is
        # built in this dead interpreter instead, which surfaces much later as
        # `image "pyimageN" doesn't exist`.
        try:
            logger.info("shutdown complete")
            shutdown_logging()
        except Exception:
            pass
        finally:
            try:
                self.destroy()
            except Exception:
                pass
